import { useEffect, useRef, useState } from 'react';
import { ArrowDownUp, ArrowRight, BookOpen, Box, Braces, ChevronDown, ChevronRight, CircleHelp, Clock3, Database, FilePlus2, FlaskConical, GitBranch, Layers3, LoaderCircle, Network, Orbit, Search, ScanLine, SlidersHorizontal, Sparkles, Terminal, TriangleAlert } from 'lucide-react';
import { request } from './api';
import { inputDateTime, dateBoundary } from './helpers.mjs';
import Detail from './Detail';
import Ingest from './Ingest';
import Evaluation from './Evaluation';
import ProfilePicker from './ProfilePicker';
import { IntegratedViews } from './IntegratedViews';
import './integrated-views.css';
import { AssertionList, GraphView, TimelineView, VectorView } from './Projections';
import type { Assertion, Example, Meta, Profile, ProfileList, QueryResult, Scope } from './types';

type Page = 'workbench' | 'ingest' | 'evaluation';
type Layer = 'graph' | 'vector' | 'timeline' | 'graph-rag' | 'graph-rag-timeline';
const initialScope: Scope = {valid_at:'2026-09-12T00:00:00Z', known_at:'2026-09-12T23:59:59Z', world:'main', plane:'all', perspective:'all'};
export default function App() {
  const [profiles, setProfiles] = useState<Profile[]>([]), [profileId, setProfileId] = useState<string | null>(null), [profileError, setProfileError] = useState('');
  const profileRequest = useRef(0);
  async function loadProfiles() {
    const generation = ++profileRequest.current; setProfileError('');
    try {const data = await request<ProfileList>('/api/profiles'); if (generation !== profileRequest.current) return; setProfiles(data.profiles); let saved: string | null = null; try {saved = localStorage.getItem('chronoverse.profile');} catch {} setProfileId(data.profiles.some(item => item.id === saved) ? saved : data.default_profile_id);}
    catch (err) {if (generation === profileRequest.current) setProfileError(err instanceof Error ? err.message : String(err));}
  }
  useEffect(() => {loadProfiles(); return () => {profileRequest.current += 1;};}, []);
  function switchProfile(id: string) {profileRequest.current += 1; setProfileId(id); try {localStorage.setItem('chronoverse.profile', id);} catch {}}
  async function createProfile(name: string) {const profile = await request<Profile>('/api/profiles', {name}); setProfiles(previous => [...previous, profile]); switchProfile(profile.id);}
  if (!profileId) return <div className="profile-bootstrap"><Orbit size={35}/><h1>Open your knowledge workspace.</h1>{profileError ? <><p role="alert">{profileError}</p><button className="primary-button" onClick={loadProfiles}>Retry connection</button></> : <p><LoaderCircle size={15} className="spin"/> Loading local dataset profiles…</p>}</div>;
  return <Workspace key={profileId} profileId={profileId} profiles={profiles} onSwitchProfile={switchProfile} onCreateProfile={createProfile}/>;
}
function Workspace({profileId, profiles, onSwitchProfile, onCreateProfile}: {profileId: string; profiles: Profile[]; onSwitchProfile: (id: string) => void; onCreateProfile: (name: string) => Promise<void>}) {
  const [page, setPage] = useState<Page>('workbench'), [layer, setLayer] = useState<Layer>('graph-rag'), [meta, setMeta] = useState<Meta | null>(null), [scope, setScope] = useState<Scope>(initialScope), [query, setQuery] = useState(''), [retired, setRetired] = useState(false), [result, setResult] = useState<QueryResult | null>(null), [selected, setSelected] = useState<string | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [help, setHelp] = useState(false), [savedNote, setSavedNote] = useState('');
  const requestId = useRef(0);
  async function search(nextScope = scope, nextQuery = query, includeRetired = retired) {
    const id = ++requestId.current; setLoading(true); setError('');
    try {const data = await request<QueryResult>('/api/query', {...nextScope, query: nextQuery, include_retired: includeRetired, limit: 40}, profileId); if (id !== requestId.current) return; setResult(data); setSelected(data.results[0]?.id ?? null);}
    catch (err) {if (id === requestId.current) {setError(err instanceof Error ? err.message : String(err)); setResult(null); setSelected(null);}}
    finally {if (id === requestId.current) setLoading(false);}
  }
  useEffect(() => {let alive = true; request<Meta>('/api/meta', undefined, profileId).then(data => {if (!alive) return; setMeta(data); setScope(data.defaults); search(data.defaults, '', false);}).catch(err => {if (alive) {setError(`Cannot connect to the local API. ${err.message}`); setLoading(false);}}); return () => {alive = false; requestId.current += 1;};}, []);
  function preset(example: Example) {const next = {valid_at: example.valid_at, known_at: example.known_at, world: example.world, plane: example.plane, perspective: example.perspective}; setScope(next); setQuery(example.query); setRetired(false); setSavedNote(''); search(next, example.query, false);}
  function created(assertion: Assertion) {const next = {valid_at: assertion.valid_from, known_at: new Date().toISOString(), world: assertion.world, plane: assertion.plane, perspective: assertion.perspective}; setScope(next); setQuery(assertion.subject); setPage('workbench'); setRetired(false); setSavedNote('Your assertion is now in the local ledger.'); request<Meta>('/api/meta', undefined, profileId).then(setMeta).catch(() => {}); search(next, assertion.subject, false);}
  function imported(next: Scope) {setScope(next); setQuery(''); setRetired(false); setPage('workbench'); setSavedNote('Imported knowledge is ready in this dataset profile.'); request<Meta>('/api/meta', undefined, profileId).then(setMeta).catch(() => {}); search(next, '', false);}
  const activeAssertion = result?.results.find(item => item.id === selected) ?? null;
  const scopeChanged = result && (Date.parse(scope.valid_at) !== Date.parse(result.scope.valid_at) || Date.parse(scope.known_at) !== Date.parse(result.scope.known_at) || scope.world !== result.scope.world || scope.plane !== result.scope.plane || scope.perspective !== result.scope.perspective || query !== result.query);
  const select = (id: string) => {setSelected(id);};
  return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#" onClick={event => {event.preventDefault(); setPage('workbench');}} aria-label="Chronoverse home"><span className="brand-symbol"><Orbit size={25}/></span><span>chronoverse<span className="brand-dot">.</span></span></a><div className="sidebar-profile"><ProfilePicker profiles={profiles} selected={profileId} onSelect={onSwitchProfile} onCreate={onCreateProfile}/></div><div className="nav-label">EXPLORE</div><nav aria-label="Main navigation"><button aria-label="Workbench" className={page === 'workbench' ? 'active' : ''} onClick={() => setPage('workbench')}><Network size={17}/> Workbench <span className="nav-active-dot"/></button><button aria-label="Ingest knowledge" className={page === 'ingest' ? 'active' : ''} onClick={() => setPage('ingest')}><FilePlus2 size={17}/> Ingest knowledge</button><button aria-label="Evaluation" className={page === 'evaluation' ? 'active' : ''} onClick={() => setPage('evaluation')}><FlaskConical size={17}/> Evaluation</button></nav><div className="sidebar-layers"><div className="nav-label">KNOWLEDGE DIMENSIONS</div><div><i className="cyan"/><span>Vector relevance</span><ScanLine size={13}/></div><div><i className="lilac"/><span>Graph connections</span><GitBranch size={13}/></div><div><i className="amber"/><span>Temporal context</span><Clock3 size={13}/></div></div><div className="sidebar-bottom"><div className="local-status"><span className={`live-dot ${meta ? '' : 'offline'}`}/><div><strong>{meta ? 'Local ledger connected' : 'Connecting to ledger'}</strong><span>{meta ? `${meta.counts.assertions} assertions · ${meta.counts.events} events` : 'Waiting for the API'}</span></div></div><button className="help-button" onClick={() => setHelp(!help)}><CircleHelp size={16}/> How Chronoverse works <ArrowRight size={13}/></button><div className="version-line"><span>LOCAL POC</span><span>v0.1</span></div></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><span>Workspace</span><ChevronRight size={13}/><strong>{page === 'workbench' ? 'Knowledge workbench' : page === 'ingest' ? 'Ingest knowledge' : 'Evaluation'}</strong></div><div className="topbar-right"><div className="mobile-profile"><ProfilePicker profiles={profiles} selected={profileId} onSelect={onSwitchProfile} onCreate={onCreateProfile}/></div><span className="local-badge"><span className="live-dot"/> Local environment</span><button className="icon-button" onClick={() => setHelp(!help)} aria-label="Show product explanation"><CircleHelp size={17}/></button><span className="avatar">CV</span></div></header>
    {help && <div className="help-banner"><BookOpen size={20}/><div><strong>Knowledge, with its context intact.</strong><p>Start with a query. Filter the world, plane, and perspective. Set when a claim applies and what the system knew. Inspect the same evidence through graph, vector, and timeline views. Historical belief does not become physical fact.</p><p><Terminal size={13}/> MCP clients can query the same ledger through the read-only server. See the project README for connection instructions.</p></div><button className="icon-button" onClick={() => setHelp(false)} aria-label="Close explanation">×</button></div>}
    <main>{page === 'ingest' ? <Ingest key={profileId} meta={meta} profileId={profileId} onCreated={created} onImported={imported} onImportCommit={next => {setScope(next); setQuery(''); setRetired(false); request<Meta>('/api/meta', undefined, profileId).then(setMeta).catch(() => {}); search(next, '', false);}}/> : page === 'evaluation' ? <Evaluation key={profileId} profileId={profileId}/> : <>
      <div className="workbench-intro"><div><div className="page-eyebrow"><span className="tiny-orbit"/> KNOWLEDGE IN CONTEXT</div><h1>The answer changes.<br className="mobile-break"/> Keep the history.</h1><p className="page-subtitle">Explore what is claimed, how it connects, and when it was known.</p></div><div className="model-label"><Layers3 size={19}/><div><strong>RAG + Graph + Time</strong><span>One evidence-backed view</span></div></div></div>
      <section className="query-panel" aria-label="Query and scope controls"><form onSubmit={event => {event.preventDefault(); setSavedNote(''); search();}}><div className="search-row"><Search size={20}/><input aria-label="Search knowledge" data-testid="search-input" value={query} onChange={event => setQuery(event.target.value)} placeholder="Ask your knowledge a question, or explore all assertions…"/><button className="primary-button" aria-label="Explore" disabled={loading} type="submit">{loading ? <LoaderCircle size={15} className="spin"/> : <ArrowRight size={16}/>}<span>{loading ? 'Exploring…' : 'Explore'}</span></button></div><div className="scope-row"><label><span><Box size={12}/> World</span><select aria-label="World" value={scope.world} onChange={event => setScope({...scope, world:event.target.value})}>{(meta?.worlds || ['main']).map(value => <option key={value}>{value}</option>)}</select></label><label><span><Layers3 size={12}/> Plane</span><select aria-label="Epistemic plane" value={scope.plane} onChange={event => setScope({...scope, plane:event.target.value})}>{['all',...(meta?.planes || []).filter(value => value !== 'all')].map(value => <option key={value} value={value}>{value === 'all' ? 'All planes' : value}</option>)}</select></label><label><span><SlidersHorizontal size={12}/> Perspective</span><select aria-label="Perspective" value={scope.perspective} onChange={event => setScope({...scope, perspective:event.target.value})}>{['all',...(meta?.perspectives || []).filter(value => value !== 'all')].map(value => <option key={value} value={value}>{value === 'all' ? 'All perspectives' : value}</option>)}</select></label><div className="time-controls"><label><span className="amber-text"><Clock3 size={12}/> Valid at · UTC</span><input aria-label="Valid at UTC" type="datetime-local" required value={inputDateTime(scope.valid_at)} onChange={event => event.target.value && setScope({...scope, valid_at:dateBoundary(event.target.value)!})}/></label><span className="clock-divider"><ArrowDownUp size={13}/></span><label><span className="cyan-text"><Database size={12}/> Known at · UTC</span><input aria-label="Known at UTC" type="datetime-local" required value={inputDateTime(scope.known_at)} onChange={event => event.target.value && setScope({...scope, known_at:dateBoundary(event.target.value)!})}/></label></div></div></form>{!!meta?.examples.length && <div className="query-extras"><span className="example-label"><Sparkles size={12}/> Try a lens</span><div className="example-buttons">{meta?.examples.map((example, index) => <button key={`${example.label}-${index}`} onClick={() => preset(example)} title={`Valid: ${example.valid_at}; known: ${example.known_at}`} disabled={loading}>{example.label}<ArrowRight size={11}/></button>)}</div></div>}</section>
      {error && <div className="error-banner" role="alert"><TriangleAlert size={17}/><span>{error}</span><button onClick={() => search()}>Retry</button></div>}{savedNote && <div className="saved-note" role="status">{savedNote}</div>}
      <div className="results-heading"><div><span className="live-dot lilac"/><strong>{loading ? 'Retrieving scoped evidence' : `${result?.results.length ?? 0} assertions`}</strong><span className="muted">{result ? `from ${result.eligible_count} eligible records` : 'Evidence appears here'}</span>{scopeChanged && <span className="pending-badge">Unapplied changes · press Explore</span>}</div><label className="checkbox-label"><input type="checkbox" checked={retired} onChange={event => {setRetired(event.target.checked); search(scope, query, event.target.checked);}}/> Include retired</label></div>
      {result && result.conflicts.length > 0 && <div className="conflict-banner"><TriangleAlert size={17}/><div><strong>{result.conflicts.length} unresolved {result.conflicts.length === 1 ? 'conflict' : 'conflicts'} in this scope</strong><span>{result.conflicts.map(conflict => `${conflict.subject}: ${conflict.objects.join(' / ')}`).join(' · ')}. Relevance does not decide truth.</span></div></div>}
      <div className={`workbench-layout ${loading ? 'is-loading' : ''}`} aria-busy={loading}><section className="projection-panel"><div className="projection-header"><div className="layer-tabs" role="tablist" aria-label="Knowledge visualization layer"><button role="tab" aria-selected={layer === 'graph-rag'} className={layer === 'graph-rag' ? 'active graph-tab' : ''} onClick={() => setLayer('graph-rag')}><Layers3 size={15}/> Graph-RAG</button><button role="tab" aria-selected={layer === 'graph-rag-timeline'} className={layer === 'graph-rag-timeline' ? 'active timeline-tab' : ''} onClick={() => setLayer('graph-rag-timeline')}><Clock3 size={15}/> Graph-RAG + Time</button><button role="tab" aria-selected={layer === 'graph'} className={layer === 'graph' ? 'active graph-tab' : ''} onClick={() => setLayer('graph')}><Network size={15}/> Graph</button><button role="tab" aria-selected={layer === 'vector'} className={layer === 'vector' ? 'active vector-tab' : ''} onClick={() => setLayer('vector')}><ScanLine size={15}/> Vector</button><button role="tab" aria-selected={layer === 'timeline'} className={layer === 'timeline' ? 'active timeline-tab' : ''} onClick={() => setLayer('timeline')}><Clock3 size={15}/> Timeline</button></div><span className="projection-scope"><span className="live-dot"/> Same scoped evidence</span></div>
      {loading && !result ? <div className="state-panel" role="status"><LoaderCircle className="spin" size={28}/><h3>Opening the knowledge ledger</h3><p>Loading real assertions and their context…</p></div> : !result?.results.length ? <div className="state-panel"><Search size={30}/><h3>{error ? 'The ledger is unavailable' : meta?.counts.assertions === 0 ? 'This profile is ready for your knowledge.' : 'No assertions in this slice of time.'}</h3><p>{error ? 'Check that the local API is running, then retry.' : meta?.counts.assertions === 0 ? 'Upload a PDF, TXT, or Markdown file, or add your first assertion.' : 'Try another query, widen the plane or perspective, or choose a different knowledge date.'}</p><button className="primary-button" onClick={() => setPage('ingest')}><FilePlus2 size={15}/> Upload knowledge</button><button className="secondary-button" onClick={() => {const next = meta?.defaults || initialScope; setScope(next); setQuery(''); search(next, '', false); setRetired(false);}}>Reset to default scope</button></div> : <div role="tabpanel" aria-label={`${layer} projection`}>{layer === 'graph-rag' || layer === 'graph-rag-timeline' ? <IntegratedViews result={result} selected={selected} onSelect={select} mode={layer}/> : layer === 'graph' ? <GraphView data={result} selected={selected} onSelect={select}/> : layer === 'vector' ? <VectorView data={result} selected={selected} onSelect={select}/> : <TimelineView data={result} selected={selected} onSelect={select}/>}</div>}
      <div className="assertions-heading"><span><Braces size={14}/> Evidence ledger</span><span>Relevance score ≠ truth</span></div>{result && <AssertionList items={result.results} selected={selected} onSelect={select}/>}</section><Detail key={`${profileId}-${selected}`} profileId={profileId} assertion={activeAssertion} scope={result?.scope || scope} onClose={() => setSelected(null)} onChanged={knownAt => {const next = {...scope, known_at: knownAt}; setScope(next); setRetired(true); setSavedNote('Lifecycle event recorded. Knowledge time advanced to show the change.'); request<Meta>('/api/meta', undefined, profileId).then(setMeta).catch(() => {}); search(next, query, true);}}/></div>
      <footer className="workbench-footer"><span><ShieldIcon/> Evidence preserved. Context explicit. History never overwritten.</span><span>SQLite ledger <i/> {meta?.retrieval.name || 'Local retrieval'}</span></footer>
    </>}</main></div></div>;
}
function ShieldIcon() {return <Database size={12}/>;}
