import { useEffect, useState } from 'react';
import { ArrowUpRight, Check, Clock3, FileText, GitCommitHorizontal, History, ShieldCheck, X } from 'lucide-react';
import { request } from './api';
import { inputDateTime, eventBoundary, safeSourceUrl } from './helpers.mjs';
import type { Assertion, Scope } from './types';
const displayDate = (value: string | null) => value ? value.replace('T', ' ').slice(0, 16) + ' UTC' : 'Open-ended';
export default function Detail({ assertion, scope, profileId, onChanged, onClose }: {profileId: string; assertion: Assertion | null; scope: Scope; onChanged: (knownAt: string) => void; onClose: () => void}) {
  const [eventOpen, setEventOpen] = useState(false), [eventType, setEventType] = useState('retract'), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [editedEffective, setEditedEffective] = useState<string | undefined>(undefined);
  useEffect(() => {setEditedEffective(undefined);}, [scope.valid_at, assertion?.id]);
  async function saveEvent(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!assertion) return;
    const values = new FormData(event.currentTarget); setBusy(true); setError('');
    const recordedAt = new Date().toISOString();
    try { await request(`/api/assertions/${encodeURIComponent(assertion.id)}/events`, {type: eventType, effective_at: eventBoundary(scope.valid_at, editedEffective), recorded_at: recordedAt, reason: values.get('reason'), source: values.get('source'), replacement_id: eventType === 'retract' ? null : values.get('replacement_id')}, profileId); setEventOpen(false); onChanged(recordedAt); }
    catch (err) { setError(err instanceof Error ? err.message : String(err)); }
    finally { setBusy(false); }
  }
  if (!assertion) return <aside className="detail-panel empty-detail"><ShieldCheck size={28}/><h3>Follow the evidence.</h3><p>Select an assertion, graph node, or connection to inspect its source and history.</p></aside>;
  return <aside className="detail-panel" data-testid="evidence-detail"><div className="panel-heading"><span><FileText size={15}/> Evidence inspector</span><button className="icon-button" aria-label="Close evidence inspector" onClick={onClose}><X size={16}/></button></div><div className="detail-body">
    <div className="detail-badges"><span className={`plane-pill ${assertion.plane}`}>{assertion.plane}</span><span className={`status ${assertion.status}`}><i/>{assertion.status}</span></div>
    <h3 className="detail-statement">{assertion.subject}<span>{assertion.predicate.replaceAll('_', ' ')}</span>{assertion.object}</h3>
    {assertion.summary && <p className="detail-summary">{assertion.summary}</p>}
    <div className="context-grid"><div><span>World</span><strong>{assertion.world}</strong></div><div><span>Perspective</span><strong>{assertion.perspective}</strong></div></div>
    <div className="detail-section"><h4><Clock3 size={14}/> Temporal context</h4><dl className="date-list"><dt>Valid from</dt><dd>{displayDate(assertion.valid_from)}</dd><dt>Valid until</dt><dd>{displayDate(assertion.effective_valid_to)}</dd><dt>First known</dt><dd>{displayDate(assertion.recorded_at)}</dd></dl><p className="tiny-note">Snapshot as known {displayDate(scope.known_at)}. End dates are exclusive.</p></div>
    <div className="detail-section"><h4><FileText size={14}/> Sources <span>{assertion.evidence.length}</span></h4>{assertion.evidence.map(evidence => <article className="source-card" key={evidence.id}><div className="source-top"><span className="source-icon"><FileText size={15}/></span>{evidence.synthetic && <span className="synthetic-tag">SYNTHETIC</span>}</div><h5>{evidence.title}</h5><blockquote>{evidence.text}</blockquote><div className="source-bottom"><span>{evidence.recorded_at.slice(0,10)}</span>{safeSourceUrl(evidence.url) && <a href={safeSourceUrl(evidence.url)!} target="_blank" rel="noopener noreferrer">Open source <ArrowUpRight size={12}/></a>}</div></article>)}</div>
    <div className="detail-section"><h4><History size={14}/> Ledger history <span>{assertion.events.length + 1}</span></h4><div className="history-event"><GitCommitHorizontal size={16}/><div><strong>Assertion recorded</strong><span>{displayDate(assertion.recorded_at)}</span></div></div>{assertion.events.map(event => <div className="history-event" key={event.id}><GitCommitHorizontal size={16}/><div><strong>{event.type}</strong><span>Known {displayDate(event.recorded_at)}</span><span>Effective {displayDate(event.effective_at)}</span><p>{event.reason}</p><small>Source: {event.source}</small>{event.replacement_id && <code>Replacement: {event.replacement_id}</code>}</div></div>)}</div>
    <details className="explanation"><summary>Why this assertion was retrieved</summary><p>{assertion.explanation}</p><dl><dt>Lexical</dt><dd>{assertion.score_breakdown?.lexical?.toFixed(3)}</dd><dt>Vector</dt><dd>{assertion.score_breakdown?.vector?.toFixed(3)}</dd><dt>Graph</dt><dd>{assertion.score_breakdown?.graph?.toFixed(3)}</dd></dl><p>These are relevance scores, not measures of truth.</p><code>{assertion.id}</code></details>
    <button className="secondary-button lifecycle-toggle" onClick={() => {setEventOpen(!eventOpen); setEditedEffective(undefined); setError('');}}><GitCommitHorizontal size={14}/>{eventOpen ? 'Cancel lifecycle event' : 'Record lifecycle event'}</button>
    {eventOpen && <form className="lifecycle-form" onSubmit={saveEvent}><p>Append an event to the immutable ledger. Earlier knowledge snapshots stay unchanged.</p><label>Event type<select value={eventType} onChange={event => setEventType(event.target.value)}><option value="retract">Retract assertion</option><option value="correct">Correct with replacement</option><option value="supersede">Supersede with replacement</option></select></label><label>Effective at (UTC)<input type="datetime-local" name="effective_at" required value={editedEffective ?? inputDateTime(scope.valid_at)} onChange={event => setEditedEffective(event.target.value)}/><small className="tiny-note">{editedEffective === undefined ? `Exact default preserved: ${scope.valid_at}` : 'Edited time uses the displayed UTC minute.'}</small></label>{eventType !== 'retract' && <label>Existing replacement assertion ID<input name="replacement_id" required placeholder="Same subject, predicate and scope"/></label>}<label>Reason<textarea name="reason" required rows={2}/></label><label>Source<input name="source" required placeholder="Evidence or decision source"/></label>{error && <p className="error-message" role="alert">{error}</p>}<button className="primary-button" disabled={busy}><Check size={14}/>{busy ? 'Recording…' : 'Append event'}</button></form>}
  </div></aside>;
}
