import { useState } from 'react';
import { ArrowRight, BookOpen, CheckCircle2, FilePlus2, FileText, Plus, ShieldCheck } from 'lucide-react';
import { request } from './api';
import Upload from './Upload';
import { dateBoundary } from './helpers.mjs';
import type { Assertion, Meta, Scope } from './types';
export default function Ingest({meta, profileId, onCreated, onImported, onImportCommit}: {meta: Meta | null; profileId: string; onCreated: (assertion: Assertion) => void; onImported: (scope: Scope) => void; onImportCommit: (scope: Scope) => void}) {
  const [mode, setMode] = useState<'upload'|'manual'>('upload');
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [created, setCreated] = useState<Assertion | null>(null);
  const now = new Date().toISOString().slice(0, 16);
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); setBusy(true); setError(''); setCreated(null);
    const recordedAt = dateBoundary(String(values.get('recorded_at')));
    try {
      const assertion = await request<Assertion>('/api/assertions', {subject: values.get('subject'), predicate: values.get('predicate'), object: values.get('object'), summary: values.get('summary'), world: values.get('world'), plane: values.get('plane'), perspective: values.get('perspective'), valid_from: dateBoundary(String(values.get('valid_from'))), valid_to: values.get('valid_to') ? dateBoundary(String(values.get('valid_to'))) : null, recorded_at: recordedAt, ...(values.get('id') ? {id: values.get('id')} : {}), evidence: [{title: values.get('evidence_title'), text: values.get('evidence_text'), url: values.get('evidence_url') || null, recorded_at: recordedAt, synthetic: values.get('synthetic') === 'on'}]}, profileId);
      setCreated(assertion); form.reset();
    } catch (err) {setError(err instanceof Error ? err.message : String(err));} finally {setBusy(false);}
  }
  const modeTabs = <div className="ingest-mode-tabs" role="tablist" aria-label="Knowledge ingestion method"><button role="tab" aria-selected={mode === 'upload'} onClick={() => setMode('upload')}><FilePlus2 size={16}/>Upload documents</button><button role="tab" aria-selected={mode === 'manual'} onClick={() => setMode('manual')}><Plus size={16}/>Write an assertion</button></div>;
  if (mode === 'upload') return <div className="ingest-page"><div className="page-eyebrow"><FilePlus2 size={14}/> GROW YOUR KNOWLEDGE</div><h1>Your sources. Their context. One place.</h1><p className="page-subtitle">Add files to {meta?.profile?.name || 'this profile'} and inspect every passage before it enters the ledger.</p>{modeTabs}<Upload key={profileId} profileId={profileId} profileName={meta?.profile?.name || 'this profile'} onExplore={onImported} onCommitted={onImportCommit}/></div>;
  return <div className="ingest-page"><div className="page-eyebrow"><FilePlus2 size={14}/> GROW THE LEDGER</div><h1>Give a claim its context.</h1><p className="page-subtitle">Add an assertion, its source, and the two dates that make it meaningful.</p>{modeTabs}
    {created && <div className="success-banner" role="status"><CheckCircle2 size={20}/><div><strong>Assertion saved to the local ledger.</strong><span>{created.subject} → {created.object} · {created.id}</span></div><button onClick={() => onCreated(created)}>Explore assertion <ArrowRight size={16}/></button></div>}
    <div className="ingest-layout"><form className="ingest-form" onSubmit={submit} data-testid="ingest-form"><section className="form-section"><div className="section-title"><span>01</span><div><h2>The assertion</h2><p>State the relationship explicitly. No automatic extraction is performed.</p></div></div><div className="form-grid three"><label>Subject<input name="subject" required placeholder="e.g. Aurora Observatory"/></label><label>Predicate<input name="predicate" required placeholder="e.g. director"/></label><label>Object<input name="object" required placeholder="e.g. Dr. Mira Chen"/></label></div><label>Context / summary<textarea name="summary" rows={2} placeholder="What should someone know when interpreting this claim?"/></label><div className="form-grid three"><label>World<input name="world" defaultValue="main" required list="world-options"/><datalist id="world-options">{meta?.worlds.map(value => <option key={value} value={value}/>)}</datalist></label><label>Epistemic plane<select name="plane" defaultValue="fact">{(meta?.planes.filter(value => value !== 'all') || ['fact','report','belief','theory','forecast','scenario']).map(value => <option key={value}>{value}</option>)}</select></label><label>Perspective<input name="perspective" defaultValue="general" required list="perspective-options"/><datalist id="perspective-options">{meta?.perspectives.filter(value => value !== 'all').map(value => <option key={value} value={value}/>)}</datalist></label></div></section>
    <section className="form-section"><div className="section-title"><span>02</span><div><h2>The two clocks</h2><p>All times are UTC. Valid-until is exclusive; leave it blank for an open interval.</p></div></div><div className="form-grid three"><label>Valid from (UTC)<input type="datetime-local" name="valid_from" defaultValue={now} required/></label><label>Valid until (UTC)<input type="datetime-local" name="valid_to"/></label><label>Recorded at (UTC)<input type="datetime-local" name="recorded_at" defaultValue={now} required/></label></div></section>
    <section className="form-section"><div className="section-title"><span>03</span><div><h2>The evidence</h2><p>Keep the original passage so every assertion can be traced to its source.</p></div></div><div className="form-grid"><label>Source title<input name="evidence_title" required placeholder="Document or publication title"/></label><label>Source URL (optional)<input type="url" name="evidence_url" placeholder="https://…"/></label></div><label>Original source text<textarea name="evidence_text" rows={5} required placeholder="Paste the exact source passage or document text…"/></label><label className="checkbox-label"><input type="checkbox" name="synthetic"/> This is synthetic demonstration evidence</label><details className="advanced-field"><summary>Optional idempotency key</summary><label>Assertion ID<input name="id" placeholder="An identical replay with this ID is safe"/></label></details></section>
    {error && <div className="error-banner" role="alert">{error}</div>}<div className="form-footer"><span><ShieldCheck size={14}/> Stored locally · Original records retained</span><button className="primary-button" disabled={busy}><Plus size={16}/>{busy ? 'Saving assertion…' : 'Add assertion'}</button></div></form>
    <aside className="ingest-help"><div className="help-symbol"><BookOpen size={24}/></div><h3>A claim is more than a sentence.</h3><p>“The director is Mira” needs a date, a source, and a perspective before it becomes useful knowledge.</p><div className="help-point"><i className="lilac"/><div><strong>Keep beliefs in their plane.</strong><p>A historical belief can be faithfully recorded without becoming a physical fact.</p></div></div><div className="help-point"><i className="amber"/><div><strong>Separate happened from learned.</strong><p>A correction received today may refer to an event last month.</p></div></div><div className="help-point"><i className="cyan"/><div><strong>Preserve disagreements.</strong><p>Competing assertions stay visible. A higher retrieval score does not settle the conflict.</p></div></div><div className="local-note"><FileText size={15}/><span>Documents are stored with your manually supplied assertion. This form does not send their text to an AI provider.</span></div></aside></div>
  </div>;
}
