export type Evidence = { id: string; title: string; url: string | null; text: string; recorded_at: string; synthetic: boolean };
export type LifecycleEvent = { id: string; assertion_id: string; type: 'supersede' | 'correct' | 'retract'; effective_at: string; recorded_at: string; reason: string; source: string; replacement_id: string | null };
export type Assertion = { id: string; subject: string; predicate: string; object: string; world: string; plane: string; perspective: string; valid_from: string; valid_to: string | null; recorded_at: string; status: string; effective_valid_to: string | null; summary: string; evidence: Evidence[]; events: LifecycleEvent[]; score: number; score_breakdown: {lexical: number; vector: number; graph: number}; explanation: string };
export type Scope = { valid_at: string; known_at: string; world: string; plane: string; perspective: string };
export type Example = Scope & { label: string; query: string };
export type Meta = { profile_id: string; profile: Profile; import_formats: string[]; worlds: string[]; planes: string[]; perspectives: string[]; defaults: Scope; counts: {assertions: number; events: number}; retrieval: {name: string; description: string}; examples: Example[] };
export type QueryResult = { profile_id: string; query: string; scope: Scope; results: Assertion[]; conflicts: {subject: string; predicate: string; assertion_ids: string[]; objects: string[]; explanation: string}[]; graph: {nodes: {id: string; label: string; kind: string}[]; edges: {id: string; source: string; target: string; label: string; assertion_id: string; plane: string; status: string}[]}; explanation: string; eligible_count: number; retrieval: {name: string; description: string} };
export type Evaluation = { profile_id?: string; evaluation_profile_id?: string; dataset: string; disclaimer: string; cases: {name: string; query: Scope & { query: string; limit: number; include_retired: boolean }; forbidden_ids: string[]; expected_ids: string[]; baseline_ids: string[]; chronoverse_ids: string[]; baseline_pass: boolean; chronoverse_pass: boolean; explanation: string}[]; summary: {cases: number; baseline_passed: number; chronoverse_passed: number} };

export type Profile = {id: string; name: string; created_at: string; is_demo: boolean; counts?: {assertions: number; events: number}};
export type ProfileList = {profiles: Profile[]; default_profile_id: string};
export type ImportPreview = {preview_id: string; profile_id: string; filename: string; format: string; content_hash: string; assertion_count: number; document_count: number; warnings: string[]; sample_assertions: Assertion[]; recommended_scope: Scope};
export type ImportCommit = {profile_id: string; preview_id: string; filename: string; content_hash: string; inserted_count: number; existing_count: number; assertion_ids: string[]; recommended_scope: Scope};
